version: '3'
services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb_data:/data/db
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
volumes:
  mongodb_data:
